---
nginx::nginx_vhosts:
  'aptly':
    proxy: 'http://medallia-aptly-repo.s3-website-us-west-2.amazonaws.com'
    proxy_set_header:
      - 'Host medallia-aptly-repo.s3-website-us-west-2.amazonaws.com'

nginx::nginx_locations:
  'healthcheck':
    location: /healthcheck
    vhost: 'aptly'
    location_custom_cfg:
      return: 200
  'key':
    location: /key
    vhost: 'aptly'
    www_root: '/etc/nginx/www'
