---
aptly::user: 'aptly'
# Issue with aptly module to retrieve the pub key
# so I define aptly repo with apt module.
aptly::repo: false
aptly::config:
  rootDir: '/data/aptly'
  S3PublishEndpoints:
    medallia-aptly-repo:
      region: 'us-west-2'
      bucket: 'medallia-aptly-repo'
      acl: 'public-read'
