---
profiles::resources::users:
  'aptly':
    comment: 'User aptly'
    uid: 1001
    groups: [ 'users' ]
    home: '/home/aptly'

profiles::resources::files:
  '/data':
    ensure: directory
    owner: aptly
    group: users
    mode: '744'
  '/data/aptly':
    ensure: directory
    owner: aptly
    group: users
    mode: '744'
