---
profiles::resources::users:
  'aptly':
    comment: 'User aptly'
    uid: 1001
    groups: [ 'users' ]
    home: '/home/aptly'

profile::resources::files:
  '/data/aptly':
    ensure: directory
    owner: aptly
    mode: 744
